from keybert import KeyBERT

doc = """
        1 star because, no matter what the facility itself has to offer, the parking is such a joke its not worth trying to workout here. All students have to pay at least $5 an hour every time just to park NEAR the gym. Non-students can park for free. Students (including graduate students who cant live on campus and dont live within walking distance), you know, the people the university is supposedly designed to serve and the ones who pay outrageous tuition to keep the school operating, need to pay at least $5 for parking every time they go to the gym. If you work out 5-6 times a week like what is commonly required to stay fit, you are paying $25-$30 A WEEK! You can get luxury gym memberships for less than that, and Yates is nothing even remotely close to a luxury gym. Theres no metro to GU and the GUTS is a joke of a shuttle. It runs irregularly and only a handful of times a day. So good luck finding alternatives to parking.Transportation at Georgetown in general is such a nightmare it makes me almost regret choosing to get an education here. The school does absolutely nothing to help students access THEIR OWN campus. Instead they actively work to make it harder for students to have campus access. Hope you like fighting and stressing just to make it to class and studying off campus because every second you want to spend on your own campus costs you more money. Youre a GU student and think you get access to all these facilities and resources because you pay one of the highest tuition rates in world? Hahaha! The administration here would like you to think again. Its insanity.
        Realistically, and compared to the other universities' gyms in DC, GT's gym is incredible. It's spacious, well laid out, contains everything one would need. However, it's not without flaws: more machines would be great, an extra rack and bench or two would be helpful, and please can we fix the T-Bar machine!
        No music, weight racks have no labels. Highly recommend labeling weight racks to organize dumbbells. I wish it opened earlier so I can go before work or early classes. Included with tuitionunsure how much I can complain :/
        It would be 5/5 if they only had a functioning sauna and better AC.
        It has all the facilities no doubt, but the pathways are a bit crypted just like hogwarts in harry potter world. No clear markings or signs to guide you, and its easy to feel lonely in the huge compound. Information desk is quite helpful. Some of the alleys need renovation or at least cleaning.
        Normally, I absolutely despise working out, there is nothing that makes me less excited. However, I absolutely love Orangetheory! At my home spot, the Georgetown location, I have never felt more welcome, more motivated and inspired to become the best version of myself. I have never been so dedicated to my overall health. Coaches Flora, Tana, and Jade are absolutely amazing, and I enjoy coming to each and every class. The team aspect and camaraderie with the people that I work out with is an atmosphere that cant be duplicated anywhere else. Joining Orangetheory Georgetown is one of the best decisions I have made this year!
        Orangetheory is a community - great people and great workouts. I love the coaches, front desk staff, and studio manager. The head coach (Flora) is amazing and keeps me accountable. I love that the workouts change every day. I highly recommend OTF!!! Its fast paced and fun!
        I love Orangetheory Georgetown! I have been to many different OT locations around the country and none of them compare to the quality of Georgetowns studio. The facilities are very clean which helps me feel comfortable with my workout space. The coaches and staff are all encouraging and have helped me make progress towards my fitness goals. They treat the members like part of the community! I always recommend all my friends try out OTF Georgetown!
        Great, fun workout + supportive community helping you along the way.  I really like the fact that youll see all ages, all genders and all levels of fitness (including lots of people who are just starting out or dealing with injuries/limitations as I am, etc).   The coaches are there to root you on and help you along your journey.  Its been a great way for me to improve myself in a way that I wouldnt on my own.   Grateful theyre part of the neighborhood.
        Orange Theory Georgetown is wonderful.The workouts have a lot of variety and can be done by people of all ages and ability.  Im often the oldest person in the class but I am able to do everything at my pace.  It has also had a huge impact.  Ive been doing it for a few months and really notice the difference.The coaches are great.  They are cheerful and encouraging (hard to be at 6:15am) but also give advice and correction when needed.  They are great at what they do and are skilled and considerate.I have not been to other OTFs in the area so cant compare but I can recommend this one 100%.
        I've had several other personal trainers in the past but I can confidently say that Daniel at Fitness Together has been by far the best. Each program he creates challenges me and is tailored to my skills as well as places I need to improve! I'm currently pregnant and still feel comfortable pushing myself and training under his guidance. I would highly recommend both Daniel and Fitness Together for anyone interested in improving their fitness.
        Fitness Together has an incredible team and takes a holistic approach to fitness and health. The trainers at FT are professional, experienced and I trust them completely with my health and fitness goals. I initially joined FT to get in shape for my wedding but more importantly, I was looking for an organization that had the nutrition component to educate myself for long term success. The FT team customizes programs based on your goals and challenges you (with direction and support). I love the shared coaching experience because no matter who you work with at FT, your program is consistent, and you know youre getting the same quality of training from each trainer. From a Nutrition standpoint, Kristina has been an incredible help in learning what my body needs to fuel those exercises and cut back on my sweet tooth. As Im entering a new chapter of my life, the team at FT is helping me set up a healthy lifestyle and challenging me to be the best version of myself. I would recommend FT to any and everyone!
        Been training here for about 6 months - will leave a longer review later but for now - 1) one of the great things about this place is the diverse experience you get training with a number of different experts, each of which brings something unique to the table, 2) a big thank you to Hillary & Kat for being tough and fun to work with in my recent early mornings. I dont appreciate how sore I keep feeling but I can tell the difference:), 3) the rest will get separate forthcoming thank yous!  Love this place.
        A customer for about a year, this fitness studio is superior in every way:  knowledge and enthusiasm of the staff, cleanliness, and equipment.  Hillary is precise and patient, an excellent trainer.
        I have been training with Hillary at Fitness Together in Georgetown for four months.  She is engaging, extremely knowledgeable, disciplined, thorough, focused, confident and motivating.  I can't think of a better combination of qualities in a trainer.  Based not only on how I feel, but also on empirical evidence, I am in much better shape now than I was when I started at Fitness Together. She works you hard, but there's a payoff.  I am greatly in her debt.I am now a year into working with Hillary as my trainer at Fitness Together.  I can only emphatically second my assessment of her made at four months above.  Her dedication to the profession is so obvious, she is a stickler for form and posture, listens to feedback from me and adjusts accordingly.  In addition to the. qualities I outlined in my first post, she has a charm that really connects with her clients, reading mood and affect very well.  Even though she works me hard, I hate to say it, but I look forward to our training sessions.
        Great facilities, but even as a student you need to rent most of the sports equipment there. Bring your own towel!
        Great place play Basketball and college football
        Beautiful facility
        great facility.
        Hardly anyone is allowed to use it
        I have taken gym classes across the city and Definitions is consistently one of my favorites. Earl and DeShay make you feel so welcomed and motivated. The classes are well organized and challenging. I left each class feeling accomplished and stronger. Would HIGHLY recommend!
        My daughters  Christmas present to me were  several sessions with the trainer Earl. This is a great gym for an older person. Earl is a patient, kind instructor who is customizing my fitness program. I feel like I am in good hands.
        Took the MRT CLIMB class here with Earl. Earl is the sweetest, most helpful instructor I've ever had. He puts in the effort to learn everyone's names, and makes sure you're doing well during the class by checking in on you and re-explaining exercises if necessary.
        I used Definitions for a few months and sadly I moved too far away for it to make sense anymore. But it is awesome. You can tell it's a small business, personally run, and the instructors were both really good and very welcoming. It's intimidating to try a new gym and all new movements but they are both so good at making you feel at ease (just let them know it's new!). The workouts were really interesting, very hard, and varied.
        DeShay and Earl rock - they make you feel like your presence is valued. They challenge and support you wherever you are in the workout arena. The space is also clean and bright 
        Yes, its a cult. But its my cult! All jokes aside, the community here is so kind and welcoming. The instructors are all wonderful, and more than willing to help you along your SoulCycle journey. I was intimidated to go here at first because I felt like I wasnt fit enough. But really, it doesnt matter. The point is just to do what makes you feel good! Personally, my progress has been impressive, and I think anyone else could do the same! PS: If youre a student, make sure to get the student discount for their classes
        As someone who is VERY out of shape and intimidated by working out, Soul Cycle at Georgetown is very welcoming! My first class was the One Direction vs. 5SOS and I left feeling AMAZING! Thank you so much @ Soul Cycle Georgetown and I cant wait for my next class!
        It was my First time coming here. The staff was phenomenal!!! They were the absolute sweetest. I felt so at home and I  didnt feel out of place like I did at my old cycling place. I cant wait to go back!!
        Wow! One of the best soul cycles Ive been to! Down to the assistants! I was Helped by Jordan who educated me on how to ride the bike to the best comfort based on my height and arm length! He made a great first impression for Georgetown soul cycle. Thank you again Jordan and the rest of the staff!
        Great workout, very upbeat staff. But three stars because it was WAY TOO LOUD!  I couldn't hear anything the instructor was yelling at us - it was all just noise on top of noise. I went with my niece who has been to Soulcycle in other cities and she agreed this class was way too loud. Three hours later my ears are still ringing.
        I cannot recommend Fitness Foundation Georgetown enough! I have been training with them since June 2021. My trainer is Michaela and I am so happy with my fitness results. I love how they tailor your fitness plan to you. I highly recommend this gym. They have a clean facility, friendly staff that give you positive marks so you keep reaching your goals. Kimior is also great, he gives excellent tips on nutrition and answers any fitness questions I may have. 5 stars across the board! Thank you Fitness Foundation Georgetown for helping me reach my goals with my fitness journey:)
        I've been working out at Foundation Fitness of Georgetown for 6 months and it's been a great experience. The trainers are friendly, knowledgable and have helped me toward my goals. They provide a lot of variety in their workouts and make sure that I'm working primary and secondary muscles.I've spent most of my time with Michaela and would recommend her to everyone. She provides good recommendations on technique, pushes me out of my comfort zone and helps me train in ways that I couldn't on my own. She's easy to talk to and fun to be around, so the workouts go quick.
        I have been very happy with my training at Foundation Fitness. My trainer (Michaela) is awesome.  She does a great job of tailoring my workouts (using free weights, plyos, and stretching) to my goals. The gym itself has good equipment and is no-frills, which probably allows for the reasonable prices.  I highly recommend checking them out!
        I was really dreading returning to the gym after a couple of COVID years working out at home- and I was skeptical Id be able to accomplish more in a gym environment than I was able to on my own at home but a friend told me about Foundation Fitness and Im so grateful! It has totally changed my thinking about gyms and what I can do! The trainers are amazing. You walk in and its a VIP experience every time. You dont feel like youre walking into a big box gym and getting lost in the crowd at all. You get custom workouts with your trainer who knows you and your goals every time AND theres no awkwardly navigating sharing equipment or trying to figure out new ways to challenge your body. Just outsource the thinking to the experts!! Im stronger than Ive ever been and genuinely look forward to going to the gym. I even miss it on off days! Highly, highly recommend.
        Had a great experience here at foundation fitness. The staff was very accommodating to our needs in terms of the program for us. I think the biggest highlight was their ability to modify workouts to cater to our physical needs/restrictions and areas of improvement.Also the staff was just overall always happy to be there and passionate about fitness!
        I love the space and professionalism. The best Pilates Ive ever experienced. I worked with Tara and shes so passionate about the equipment, safety and fun challenges.
        Just experienced my first Muscular Activation Technique session with Jen.  Amazing.  I came in with pain in my knee.  Jen manipulated, prodded, tested, prodded, worked with extreme precision on activating the nerves so that my knee and foot muscle were performing better.  The key as I understood it was to get the inactive 'sub' muscles to kick into gear and offer more and balanced support.  I asked to see her again this week.
        Beautiful space.  Lissette and Alma are awesome!  I've recently started seeing Alma for M.A.T. (Muscle Activation Technique) and it has worked wonders for my various injuries and instabilities.
        Convenient location in Georgetown offering Pilates and an array of personalized fitness options.  I'll have to try the boxing training next time.
        Just awesome
        The Body You Want is an absolutely awesome gym. I have worked closely with Josef and Matt, and they have both taught me so much about how to build strength and burn fat. I had previously lost 80 lbs on my own, and they helped me to transform my body even further, and taught me things about nutrition and fitness that I didn't know (and I thought I knew a lot!) The trainers really really care about your health and well-being, unlike my experience at bigger gyms or even more corporate studios in the DC area. What I really liked was the fact that everyone at this gym was different - different ages and levels of fitness, and everyone had their own custom plan. The extra support and training is totally worth it, and the entire staff is always willing to answer questions and help you get to your personal best. Feel free to reach out to me if you want more information about this gym, I'd be a happy to recommend personally!
        This is the best gym I have ever found.  The trainers are committed to their clients.  The clients are supportive of each other and motivate each other to reach their own fitness goals.  I have been a member for over 7 years and still get to the gym 4-5 days a week because I love the place, the trainers and the clients!
        Best gym ever.  If you are reading this, you need to join.Don't want to workout in a cookie cutter gym?  This is the place.Don't want to pay a personal trainer a small ransom?  This is the place.True180 has small group training sessions (basically personal training), classes, and open gym times.  You choose your adventure.  Be your own Dora the Explorer.Also, this gym is a community.  There are women and men, young and old, fitness fanatics and those just starting their fitness journey.  It's a cool mix of supportive and upbeat people.
        Love this gym. It's a regular joe's gym for people who are serious about getting personalized training. T180 has a real family vibe and the trainers will work with you on your goals. I joined in 2015 (I think) with nagging injuries that they helped me work through and last year they prepped me to fun my first marathon completely injury-free. Solid advice on fitness focused nutrition too.
        Best gym in Washington DC. Where do I start ? Okay, this gym will change your life and your perspective on working out. I have cp which is a disability that is different for every person that has it. For me, its left me wheelchair bound. That being said, Matt still was willing to work with me and accommodate my needs. He tailors my works out to my abilities and is committed to getting me strong and healthy. Matt, I cant thank you enough! If youre looking for a judge free environment that makes exercising fun and eating healthy sound good... this is the place for you !!!
        This is a true community gym! I signed up for a short term membership while in town for a conference/vacation, and it perfectly suited my needs for lifting heavy sh*t and a friendly environment.Miss D is an absolute joy. I'm grateful that she was open to chatting with me every morning (I can be a bit much ), and I loved watching her interact with other members. She was constantly warm, friendly, and encouraging.I read a few comments about the equipment here on Google. I agree that the equipment is a bit haphazardly placed, but I also saw very few members contributing to the maintenance and organization of the equipment. When we are members of a gym community, it is our responsibility to leave equipment in a place and state that we found it or better. I hope that folks read this message and choose the courage and confidence to be part of helping Balance be the best it can be The gym is located in the lower level of the hotel, so it's a bit hard to find, but there are always friendly hotel staff around to help.Their fridge is stocked with all the best caffeine and protein supplements, and they have a good selection of protein bars as well.Overall, I found the facilities to be clean and well suited to any strength or cardio program I wished to perform.I'll be working out here again anytime I come back to D.C. Thank you, Miss D, and thank you Balance community for the welcome and inspiration to kick butt every morning!
        3.5 months later: the equipment has not even been pretended like its going to be getting fixed. The staff here gives absolutely no regard to the people who lift here regularly. I am honestly ashamed that I keep paying for this membership that is going to have to change. Anyone searching for a gym? Go literally anywhere else
        Gym is fine but my wallet and keys were stolen from the locker. The lockers were abominable before but at least they locked. The new lockers are completely unreliable and you have to look for one that locks. For many, though, you pull hard enough and they just come right open since the locking mechanism is just cheap metal barely in contact so it can just slip open.
        Excellent staff, courteous and helpful. Good facilities. The only shortcoming tome is that the pool is designed for 3 lanes (per the lines at the bottom) but the divider on the water divides the middle lane into two equal ones (thus creating four lanes) making the two lanes in the middle a bit tight (although not unreasonably).
        Really enjoy coming to this gym. Everything is always very clean, and the staff are friendly. It can be a little tricky to find it since its entrance is through the Fairmont, but would definitely recommend to anyone who is looking for a gym in the DC area.
        I really like orange theory west end. Its a great work out and the coaches are so encouraging and positive. I signed up for the 8 classes a month package which is just enough to stay active but not too much for my schedule. The workouts are challenging and fun. West end is a great location because they have plenty of space and they include free towels you can use. The orange theory online community is also fun to interact with. Try it out for a month and see if you like it!
        I joined OTF West End about two and a half months ago and love it. The team at OTF West End is amazing! They really care about you as a member and go out of their way to help you improve your fitness - whether by giving you coaching on the proper way to do an exercise, cheering you on as youre working out, or greeting you by name with a cheerful hello when you come into the facility. You really feel like youre part of the team there. Did I mention that  they also make the workouts fun (and challenging)?!?
        I love Orangetheory. I thought I was in shape before coming here regularly, but I've seen real changes in my body, my strength and my stamina. Not to mention my mood! You get what you put into it, so it's great for every level. I feel dead at the end of every workout, which I love. The coaches and sales associates are super nice, too! Definitely recommend.
        I joined OFT a couple of months ago and I'm pretty sure it's one of the best decisions I've made. Previously, I used to attend conventional gyms, but sometimes it's complicated to organize your workout by yourself. At OTF I enjoy workouts, which are always different and this pushes me to improve my fitness and resistance. As for the staff, everyone is especially friendly and always greets you with a smile, but I would like to point out the coaches Jade and Maddie, who are always willing to advise me on how to get the most out of my workout.
        I've been a member at this studio for about 4 months now and have enjoyed every part of my experience. From the moment you walk through the door, you're greeted by the most welcoming front desk staff who make it a point to know your name and welcome you in. During your class, you're trained by top of the line coaches who ensure to check-in on everyone individually and offer any suggestions/alternatives if necessary. The amenities are amazing and it's nice that there are towels, lockers, and private showers that you can use. 100% recommend to anyone looking to meet their fitness goals or begin their journey. OT West End is the best end!
        Ive been to this location a few times and each time I find that the floors in the studios have a good amount of hair and a film of dirt. I also noticed that the showers are not cleaned between classes. I have noticed the drains were clogged with hair on a few occasions. The classes are good but it very much depends on the instructor. Also, it is worth noting that the classes are sometimes at capacity and they will turn people away who have signed up because there is zero space between mats/people in the studio. I think this is too much. They should manage this better. They shouldnt let a bunch of people walk in and then turn away those who signed up. The classes also shouldnt be so packed that people have to navigate around hitting each other, especially coming out of the pandemic. Each class is heated, which is kind of unbelievable given that it only decreases the quality and flow of air and thus increases your chances of catching whatever illnesses people may bring to the session. While you can wear a mask, its not ideal given how hot the room is and with everyone huffing and puffing nearly on top of one another its not much help. This studio really needs to manage overcrowding because it detracts from everyones experience and that is not fair given how expensive each session is. Its certainly not a stress free zone.
        My first time ever trying yoga sculpt and it has been life-changing! I love the energy in all the classes and the feeling I get after every session. I recommend it 100%
        Elizabeth is such an amazing person. My friends and I stopped by just to ask questions and she greeted us with open arms and we ended up discussing life and our yoga practice during the pandemic. She suggested doing the c1 class to get back in the grove of things. We laughed and had such a good time. You guys have such a great employee there!!
        I took the Saturday 12:30 PM sculpt class with the instructor, Emily. It was AMAZING. The flow was so great that the hour went by in a flash. I felt like I was able to get my yoga and a great workout in at once. It's definitely one of my favorite classes of all time!
        Yoga sculpt is the BEST class. Great work out, slightly heated room. I received a discount on a ten class pack on Gilt city and the classes NEVER expire which is unheard of for workout packages in DC!
        Dropped in for a two week trial class but couldnt get past a day. Maybe Im spoiled with stellar teachers and basic yoga environments, but it was impersonally taught, borderline apathetic teaching, and the pacing was comical - who needs chataranga on and off every 5 seconds like that, ever? I found myself laughing out of frustration and also how poor the class was.I also got slight attitude when I walked in too and attributed it to being in the swanky Georgetown and at a hot yoga studio.Also emailed for a refund for my two week trial to no response.Good luck DDY!
        I used to take hot power yoga classes around DC to get a workout, but never felt a real connection to the practice or a studio until walking into the Georgetown studio back in 2015. All it took was one class, and I never looked back! I've become a regular since that first class, as well as completed my 200 hr Teacher Training. The teachers and staff are all so knowledgable, helpful and FUN -- you will sweat with a smile!No matter how I am feeling before class, I always leave feeling exhilarated, refreshed and renewed - definitely helps keep me sane!
        Expert instruction paired with a welcoming, vibrant community of compassionate learners. Could not ask for a better place to practice yoga in the DC area.
        I took a hot yoga class at 9AM w Leigh Grimes. Super amazing class.  Fast paced but not crazy.  My shirt was off in less than 5 minutes Solid class.  Great music. Leigh just rocks!  I will be back.
        After coming here for 10 classes or so, I can say that down dog yoga in Georgetown is a great studio. The instructors are all friendly and knowledgeable, and the studio itself is very clean. The routine follows a similar flow each time, but theres ample room to tailor and adjust the exercise to my needs which I appreciate. Highly recommended


      """

test_doc = "Thank you @RollingOut for highlighting the Coils to Locs story!  https://t.co/o46RcjsGfI #news #coilstolocs #BlackWomen #hairloss #blackbusiness"

from rake_nltk import Rake



# Uses stopwords for english from NLTK, and all puntuation characters by
# default
r = Rake()

# Extraction given the text.
r.extract_keywords_from_text(test_doc)

# Extraction given the list of strings where each string is a sentence.
##r.extract_keywords_from_sentences(doc)

# To get keyword phrases ranked highest to lowest.
##for keyword in r.get_ranked_phrases():
##    print(keyword)

# To get keyword phrases ranked highest to lowest with scores.
##print(r.get_ranked_phrases_with_scores())
for keyword in r.get_ranked_phrases_with_scores():
    print(keyword)

##kw_model = KeyBERT()
##keywords = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 5), stop_words=None)
##print(keywords)